import React from "react";
import "./Map.css";
import Block from "./Block";

var mapData = [
  { lat: 1, long: 1, type: "land" },
  { lat: 1, long: 2, type: "land" },
  { lat: 1, long: 3, type: "land" },
  { lat: 1, long: 4, type: "land" },
  { lat: 1, long: 5, type: "land" },
  { lat: 1, long: 6, type: "land" },
  { lat: 1, long: 7, type: "land" },
  { lat: 1, long: 8, type: "land" },
  { lat: 1, long: 9, type: "land" },
  { lat: 1, long: 10, type: "land" },
  { lat: 1, long: 11, type: "land" },
  { lat: 1, long: 12, type: "land" },

  { lat: 2, long: 1, type: "land" },
  { lat: 2, long: 2, type: "land" },
  { lat: 2, long: 3, type: "land" },
  { lat: 2, long: 4, type: "land" },
  { lat: 2, long: 5, type: "land" },
  { lat: 2, long: 6, type: "land" },
  { lat: 2, long: 7, type: "land" },
  { lat: 2, long: 8, type: "land" },
  { lat: 2, long: 9, type: "land" },
  { lat: 2, long: 10, type: "land" },
  { lat: 2, long: 11, type: "land" },
  { lat: 2, long: 12, type: "land" },

  { lat: 3, long: 1, type: "land" },
  { lat: 3, long: 2, type: "land" },
  { lat: 3, long: 3, type: "land" },
  { lat: 3, long: 4, type: "land" },
  { lat: 3, long: 5, type: "land" },
  { lat: 3, long: 6, type: "land" },
  { lat: 3, long: 7, type: "land" },
  { lat: 3, long: 8, type: "land" },
  { lat: 3, long: 9, type: "land" },
  { lat: 3, long: 10, type: "land" },
  { lat: 3, long: 11, type: "land" },
  { lat: 3, long: 12, type: "land" },

  { lat: 4, long: 1, type: "land" },
  { lat: 4, long: 2, type: "land" },
  { lat: 4, long: 3, type: "land" },
  { lat: 4, long: 4, type: "land" },
  { lat: 4, long: 5, type: "land" },
  { lat: 4, long: 6, type: "land" },
  { lat: 4, long: 7, type: "land" },
  { lat: 4, long: 8, type: "land" },
  { lat: 4, long: 9, type: "land" },
  { lat: 4, long: 10, type: "land" },
  { lat: 4, long: 11, type: "land" },
  { lat: 4, long: 12, type: "land" },

  { lat: 5, long: 1, type: "land" },
  { lat: 5, long: 2, type: "land" },
  { lat: 5, long: 3, type: "land" },
  { lat: 5, long: 4, type: "land" },
  { lat: 5, long: 5, type: "land" },
  { lat: 5, long: 6, type: "land" },
  { lat: 5, long: 7, type: "land" },
  { lat: 5, long: 8, type: "land" },
  { lat: 5, long: 9, type: "land" },
  { lat: 5, long: 10, type: "land" },
  { lat: 5, long: 11, type: "land" },
  { lat: 5, long: 12, type: "land" },

  { lat: 6, long: 1, type: "land" },
  { lat: 6, long: 2, type: "land" },
  { lat: 6, long: 3, type: "land" },
  { lat: 6, long: 4, type: "land" },
  { lat: 6, long: 5, type: "ocean" },
  { lat: 6, long: 6, type: "ocean" },
  { lat: 6, long: 7, type: "ocean" },
  { lat: 6, long: 8, type: "ocean" },
  { lat: 6, long: 9, type: "land" },
  { lat: 6, long: 10, type: "land" },
  { lat: 6, long: 11, type: "land" },
  { lat: 6, long: 12, type: "land" },

  { lat: 7, long: 1, type: "land" },
  { lat: 7, long: 2, type: "land" },
  { lat: 7, long: 3, type: "land" },
  { lat: 7, long: 4, type: "ocean" },
  { lat: 7, long: 5, type: "ocean" },
  { lat: 7, long: 6, type: "ocean" },
  { lat: 7, long: 7, type: "ocean" },
  { lat: 7, long: 8, type: "ocean" },
  { lat: 7, long: 9, type: "ocean" },
  { lat: 7, long: 10, type: "land" },
  { lat: 7, long: 11, type: "land" },
  { lat: 7, long: 12, type: "land" },

  { lat: 8, long: 1, type: "land" },
  { lat: 8, long: 2, type: "land" },
  { lat: 8, long: 3, type: "ocean" },
  { lat: 8, long: 4, type: "ocean" },
  { lat: 8, long: 5, type: "ocean" },
  { lat: 8, long: 6, type: "ocean" },
  { lat: 8, long: 7, type: "ocean" },
  { lat: 8, long: 8, type: "ocean" },
  { lat: 8, long: 9, type: "ocean" },
  { lat: 8, long: 10, type: "land" },
  { lat: 8, long: 11, type: "land" },
  { lat: 8, long: 12, type: "land" },

  { lat: 9, long: 1, type: "land" },
  { lat: 9, long: 2, type: "ocean" },
  { lat: 9, long: 3, type: "ocean" },
  { lat: 9, long: 4, type: "ocean" },
  { lat: 9, long: 5, type: "ocean" },
  { lat: 9, long: 6, type: "ocean" },
  { lat: 9, long: 7, type: "ocean" },
  { lat: 9, long: 8, type: "ocean" },
  { lat: 9, long: 9, type: "ocean" },
  { lat: 9, long: 10, type: "ocean" },
  { lat: 9, long: 11, type: "land" },
  { lat: 9, long: 12, type: "land" },

  { lat: 10, long: 1, type: "ocean" },
  { lat: 10, long: 2, type: "ocean" },
  { lat: 10, long: 3, type: "ocean" },
  { lat: 10, long: 4, type: "ocean" },
  { lat: 10, long: 5, type: "ocean" },
  { lat: 10, long: 6, type: "ocean" },
  { lat: 10, long: 7, type: "land" },
  { lat: 10, long: 8, type: "ocean" },
  { lat: 10, long: 9, type: "ocean" },
  { lat: 10, long: 10, type: "ocean" },
  { lat: 10, long: 11, type: "land" },
  { lat: 10, long: 12, type: "land" },

  { lat: 11, long: 1, type: "ocean" },
  { lat: 11, long: 2, type: "ocean" },
  { lat: 11, long: 3, type: "ocean" },
  { lat: 11, long: 4, type: "ocean" },
  { lat: 11, long: 5, type: "ocean" },
  { lat: 11, long: 6, type: "land" },
  { lat: 11, long: 7, type: "land" },
  { lat: 11, long: 8, type: "ocean" },
  { lat: 11, long: 9, type: "ocean" },
  { lat: 11, long: 10, type: "ocean" },
  { lat: 11, long: 11, type: "ocean" },
  { lat: 11, long: 12, type: "land" },

  { lat: 12, long: 1, type: "ocean" },
  { lat: 12, long: 2, type: "ocean" },
  { lat: 12, long: 3, type: "ocean" },
  { lat: 12, long: 4, type: "ocean" },
  { lat: 12, long: 5, type: "land" },
  { lat: 12, long: 6, type: "land" },
  { lat: 12, long: 7, type: "land" },
  { lat: 12, long: 8, type: "land" },
  { lat: 12, long: 9, type: "ocean" },
  { lat: 12, long: 10, type: "ocean" },
  { lat: 12, long: 11, type: "ocean" },
  { lat: 12, long: 12, type: "ocean" },
];

function Map() {
  return (
    <div className="map_container">
      {mapData.map((block) => (
        <Block lat={block.lat} long={block.long} type={block.type} />
      ))}
    </div>
  );
}

export default Map;
